---
  title: Estimering av strømstøtte
  #author: "Martin Jullum, Seniorforsker Norsk Regnesentral"
  output: 
    github_document: default
    #html_document: default
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```


*Av [Martin Jullum, Norsk Regnesentral](https://nr.no/ansatte/martin-jullum/).*

# [dinstrompris.no](https://dinstrompris.no)

På [dinstrompris.no](https://dinstrompris.no) kan du ved å taste inn ditt postnummer, få opp din strømpris akkurat nå og ut morgendagen.
Prisen er medregnet både spotpris, nettleie og estimert strømstøtte.

Dette repoet inneholder all kode bak nettsiden, kode for prognosemodeller, samt daglig oppdaterte spotdata og prognoser for strømstøtten. 

Siste oppdaterte prognoser for strømstøtten kan hentes fra følgende daglig oppdaterte json-fil: (https://raw.githubusercontent.com/martinju/stromstotte/master/data/current_estimated_compensation.json).
Historiske prognoser kan hentes her:
(https://raw.githubusercontent.com/martinju/stromstotte/master/data/historic_estimated_compensation.json) 


Data/prognoser er sist oppdatert `r readLines("output/update_time.txt")`.

Litt bakgrunn om strømstøtteestimering (som etter hvert ledet frem til [dinstrompris.no](https://dinstrompris.no)) finnes [her](https://martinjullum.com/sideprojects/stromstotte/)


_________________


All modellering [Martin Jullum](https://martinjullum.com) ([jullum@nr.no](mailto:jullum@nr.no)), [Seniorforsker Norsk Regnesentral](https://nr.no/ansatte/martin-jullum/)

